Neos:
  Flow:
    persistence:
      backendOptions:
        driver: 'pdo_mysql'
        charset: 'utf8mb4'
        host: '%env:NEOS_FLOW_DEMO_DB_HOST%'
        dbname: '%env:NEOS_FLOW_DEMO_DB_NAME%'
        user: '%env:NEOS_FLOW_DEMO_DB_USERNAME%'
        password: '%env:NEOS_FLOW_DEMO_DB_PASSWORD%'
    mvc:
      routes:
        'Acme.Blog': TRUE
    core:
      phpBinaryPathAndFilename: '/home/vcap/app/php/bin/php'